### ISSUE TITLE
Issues with pg_replication pipeline

### ISSUE THREAD

**Issue by dat-a-man** [dlt-hub/dlt#1490]
### dlt version

0.4.12

### Describe the problem

When using the `dlt init pg_replication`. Here are the specific points that were observed:

1. The source accepts credentials only in the format:
credentials="postgresql://postgres:newpassword@localhost:5432/database"
It should also accept the format:
```toml
[destination.postgres.credentials]
drivername = "postgresql" # please set me up!
database = "radheshyaam" # please set me up!
password = "newpassword" # please set me up!
username = "postgres" # please set me up!
host = "localhost" # please set me up!
port = 5432 # please set me up!
````

2. When initializing with postgres, the generated templates are:

```yaml
[sources.pg_replication.credentials]
---

[destination.postgres.credentials]
---
```
Both templates require the same PostgreSQL credentials. If data is to be replicated to another Postgres database, in similar way as it be replicated to BigQuery or DuckDB?

3. When initializing with big query, the generated templates are:

```toml
[sources.pg_replication.credentials]
---

[destination.bigquery]
dataset_name = "dataset_name" # please set me up!
location = "US"

[destination.bigquery.credentials]
project_id = "please set me up!" # please set me up!
private_key = "Please set me up!" # please set me up!
client_email = "Please set me up!" # please set me up!
```

However, when running this, it prompts for:

```
[destination.postgres.credentials]
```
Which is not initialized by default. To proceed, secrets.toml should be set as:

```
[sources.pg_replication.credentials]
---

[destination.postgres.credentials]
---

[destination.bigquery.credentials]
---
```
4. When initing the following pipeline 
`dlt init pg_replication bigquery`
both `src_pl` and `dest_pl` are set to "bigquery". Where `src_pl` should be set to "postgres" and it should only require the `[sources.pg_replication.credentials]` not the `[destination.postgres.credentials]`

### Expected behavior

- [sources.pg_replication.credentials] format to work.
- Source pipeline should only be dependent on source credentials.
-"src_pl" and "dest_pl" should be set to "postgres" and "other destination" as per init

### Steps to reproduce

1. Run dlt init pg_replication postgres.
2. Observe that both credential templates require the same PostgreSQL credentials.
3. Run dlt init pg_replication bigquery.
4. Observe the prompt for [destination.postgres.credentials] and the need to manually set it.

### Operating system

macOS

### Runtime environment

Local

### Python version

3.10

### dlt data source

pg_replication

### dlt destination

Google BigQuery, Postgres
