### ISSUE TITLE
allow `yaml` as alternative to `toml` in config/secrets

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#1596]
**Background**
`dlt` stores "project" (`.dlt`) configuration in `toml` files. Here we want to support `yaml` as well. `dlt` should probe for possible files and use proper parser to read them. From the user perspective it is enough if ie. `secrets.yaml` or `secrets.yml` be present in `.dlt` folder to use it. No other configuration should be required.

Example: `.dlt/secrets.toml` and it's alternative `.dlt/secrets.yaml`:
```toml

destination.postgres.credentials="postgresql://loader:loader@localhost:5432/dlt_data"

[sources.zendesk.credentials]
subdomain = "subdomain" # Zendesk subdomain
email = "set me up" # Email used to login to Zendesk
password = "set me up" # Password for Zendesk account
token = "set me up" # For API token auth
oauth_token = "set me up" # Use Zendesk support OAuth token or Zendesk chat OAuth token

[destination.athena]
query_result_bucket="s3://dlt-ci-test-bucket"
[destination.athena.credentials]
aws_access_key_id="AK"
aws_secret_access_key="b+secret"

[destination.snowflake]
stage_name="PUBLIC.my_s3_stage"
connection_timeout=60.4
[destination.snowflake.csv_format]
delimiter="|"
include_header=false
on_error_continue=true
[destination.snowflake.credentials]
query_tag='{{"source":"{source}", "resource":"{resource}", "table": "{table}", "load_id":"{load_id}", "pipeline_name":"{pipeline_name}"}}'


[data_types]
datetime=1979-05-27T07:32:00-08:00
```

```yaml
destination:
  postgres:
    credentials: postgresql://loader:loader@localhost:5432/dlt_data
  athena:
    query_result_bucket: s3://dlt-ci-test-bucket
    credentials:
      aws_access_key_id: AK
      aws_secret_access_key: b+secret
  snowflake:
    stage_name: PUBLIC.my_s3_stage
    connection_timeout: 60.4
    csv_format:
      delimiter: '|'
      include_header: false
      on_error_continue: true
    credentials:
      query_tag: '{{"source":"{source}", "resource":"{resource}", "table": "{table}",
        "load_id":"{load_id}", "pipeline_name":"{pipeline_name}"}}'
sources:
  zendesk:
    credentials:
      subdomain: subdomain
      email: set me up
      password: set me up
      token: set me up
      oauth_token: set me up
data_types:
  datetime: 1979-05-27 07:32:00-08:00
```
We expect many users will prefer `yaml` which is shorter more opinionated regarding the layout

**Requirements**
1. We have many config providers based on `toml` format. The basic file provider, string providers, vaults and airflow providers that work with toml fragments. Luckily the `toml` part is (almost) abstracted away. We want to change the base in a way so all our downstream config providers also support yaml loading.
2. For toml we use `tomlkit` which preserves comments. This is done thanks to wrapping all Python types in tomlkit object model. If config was loaded with toml, we want to still preserve the comments to be able to write it back.
3. Both `get_value` and `set_value` must be implemented for toml and yaml
4. File provider should probe `toml`, `yaml` and `yml` files and load just one of them. If there are more files with same name but different extension, a warning message (use warn module, not logger which may not yet be configured) must explain the situation and which file got loaded
5. It would be nice if we can write both toml and yaml files back but yaml is not required. `toml` must work like it should before. We do not care for comments in yaml at this moment.

**Documentation**
1. We must document the choice in config docs
2. As a separate ticket: all `toml` snippets should become tabs with both `toml` and `yaml` representation. This is optional
