### ISSUE TITLE
Default hint of "unique" does not add a unique index

### ISSUE THREAD

**Issue by boxydog** [dlt-hub/dlt#1848]
### dlt version

1.0.0

### Describe the problem

Default hint of "unique" does not add a unique index.

See my test code and the Postgres table description below. `id2` has a unique index (because I explicitly declared one), but `id` does not.

```
                   Table "public.a_test_unique"
    Column    |       Type        | Collation | Nullable | Default 
--------------+-------------------+-----------+----------+---------
 id           | bigint            |           |          | 
 id2          | bigint            |           |          | 
 _dlt_load_id | character varying |           | not null | 
 _dlt_id      | character varying |           | not null | 
Indexes:
    "a_test_unique__dlt_id_key" UNIQUE CONSTRAINT, btree (_dlt_id)
    "a_test_unique_id2_key" UNIQUE CONSTRAINT, btree (id2)
```

### Expected behavior

I declare a default hint that "id" should be unique. For the Postgres destination, "unique" should put a unique index on the field. It does not.

### Steps to reproduce

- tar xvfz test_unique_hint.tgz
- Set up a postgres destination
- ./test_unique.py
- $ psql $DESTINATION__CREDENTIALS -c '\d a_test_unique'

`id` should have a unique index, but it does not. Separately, `id2` does have a unique index, but it was declared explicitly.

[test_unique_hint.tgz](https://github.com/user-attachments/files/17062845/test_unique_hint.tgz)

### Operating system

macOS

### Runtime environment

Local

### Python version

3.11

### dlt data source

json

### dlt destination

Postgres

### Additional information

Using hints to declare indexes may not be supported behavior. It's not documented anywhere.

However, it is what I expected, given https://dlthub.com/docs/devel/dlt-ecosystem/destinations/postgres#supported-column-hints says a unique field will get an index.

**Comment by burnash** [comment]
Hi @boxydog, sorry for the delayed response. Thanks for reporting this issue and for providing the code to reproduce it.

I attempted to reproduce the issue, but in the `test_unique_hint.tgz` in `test_unique.schema.yaml`, I noticed that the hint set for `id` is `primary_key`, not `unique`:

```yaml
  a_test_unique:
    columns:
      id:
        data_type: bigint
        primary_key: true
      id2:
        data_type: bigint
        unique: true
      _dlt_load_id:
        data_type: text
        nullable: false
      _dlt_id:
        data_type: text
        nullable: false
        unique: true
```

As of version 1.5.0, dlt does not create an index for `primary_key` hints in PostgreSQL. We welcome a pull request for this feature if you're interested in implementing it.

If you're set the `unique` hint for `id`, dlt will create a unique index just like it does for `id2`. Let me know if this resolves your issue.
