### ISSUE TITLE
Use BIGNUMERIC instead of NUMERIC when converting PostgreSQL NUMERIC fields to BigQuery with pyarrow

### ISSUE THREAD

**Issue by lfpll** [dlt-hub/dlt#2130]
### dlt version

1.4.1

### Describe the problem

When extracting tables from PostgreSQL to BigQuery, PostgreSQL's NUMERIC fields are currently being mapped to BigQuery's NUMERIC type. This can potentially lead to data truncation since PostgreSQL's NUMERIC has significantly larger precision capabilities.

### Steps to reproduce

On bigquery

```
SELECT CAST(0.9999999999999999 AS NUMERIC), CAST(0.9999999999999999 AS BIGNUMERIC);  -- 999999999999999.999999999
```

### Operating system

Linux

### Runtime environment

Kubernetes

### Python version

3.11

**Comment by sh-rp** [comment]
@lfpll I had a quick look in our source code, our bigquery destination should automatically select bignumeric if the precision indicates a need for this. are you finding otherwise? If so, I'd need some code to reproduce.

**Comment by sh-rp** [comment]
```
    def to_db_decimal_type(self, column: TColumnSchema) -> str:
        # Use BigQuery's BIGNUMERIC for large precision decimals
        precision, scale = self.decimal_precision(column.get("precision"), column.get("scale"))
        if precision > 38 or scale > 9:
            return "BIGNUMERIC(%i,%i)" % (precision, scale)
        return "NUMERIC(%i,%i)" % (precision, scale)
```

**Comment by lfpll** [comment]
@sh-rp 

# How to replicate

Create a .env

```
EXTRACT_DB_DELTA__DESTINATION__BIGQUERY__LOCATION
EXTRACT_DB_DELTA__DESTINATION__BIGQUERY__CREDENTIALS__PROJECT_ID
EXTRACT_DB_DELTA__SOURCES__SQL_DATABASE__SQL_DATABASE__CREDENTIALS__DRIVERNAME
EXTRACT_DB_DELTA__SOURCES__SQL_DATABASE__SQL_DATABASE__CREDENTIALS__HOST
EXTRACT_DB_DELTA__SOURCES__SQL_DATABASE__SQL_DATABASE__CREDENTIALS__USERNAME
EXTRACT_DB_DELTA__SOURCES__SQL_DATABASE__SQL_DATABASE__CREDENTIALS__PASSWORD
EXTRACT_DB_DELTA__SOURCES__SQL_DATABASE__SQL_DATABASE__CREDENTIALS__DATABASE
EXTRACT_DB_DELTA__SOURCES__SQL_DATABASE__SQL_DATABASE__CREDENTIALS__PORT
```

Docker-compose.yml

```
version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${EXTRACT_DB_DELTA__SOURCES__SQL_DATABASE__SQL_DATABASE__CREDENTIALS__USERNAME}
      POSTGRES_PASSWORD: ${EXTRACT_DB_DELTA__SOURCES__SQL_DATABASE__SQL_DATABASE__CREDENTIALS__PASSWORD}
      POSTGRES_DB: ${EXTRACT_DB_DELTA__SOURCES__SQL_DATABASE__SQL_DATABASE__CREDENTIALS__DATABASE}
    ports:
      - "${EXTRACT_DB_DELTA__SOURCES__SQL_DATABASE__SQL_DATABASE__CREDENTIALS__PORT}:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
  ```
  
init.sql
```
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(100),
    credit NUMERIC
);

CREATE TABLE products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    price DECIMAL(10,2)
);

INSERT INTO users (name, email, credit) VALUES
    ('John Doe', 'john@test.com',0.999999999),
    ('Jane Smith', 'jane@test.com',0.9999999);

INSERT INTO products (name, price) VALUES
    ('Laptop', 999.99),
    ('Phone', 599.99),
    ('Tablet', 299.99);
    ```
    
 python script
 ```
def load_select_tables_from_database(tables: list[TableAttributes]) -> None:
    if len(tables) > 1:
        raise ValueError("This script only supports one table for now")

    table_config = {"table_name": "users"}

    pipeline = dlt.pipeline(
        pipeline_name="extract_db_delta",
        destination='bigquery',
        dataset_name=DATASET_NAME,
        progress="log",
    )
    credentials = ConnectionStringCredentials()

    extra_table_args = {}
    extra_sql_args = {
        # "table_adapter_callback": add_dw_extraction_time_column,
    }
    
    sources = sql_database(
        credentials=credentials,
        chunk_size=10000 * 5,
        backend='pyarrow',
        include_views=True,
        **extra_sql_args,
    ).with_resources(table_config["table_name"])

    logging.info(f"Adding table: {table_config}")

    table = sources.resources[table_config["table_name"]]
    table.apply_hints(write_disposition="append", **extra_table_args)

    info = pipeline.run(sources)
    logging.info(info)
    ```
