### ISSUE TITLE
Ensure factory functions of core sources produce nice default values

### ISSUE THREAD

**Issue by sh-rp** [dlt-hub/dlt#2547]
### TLDR
After implementing #2531 we should ensure that the defaults created for the sql_database, rest_api and filesystem sources provide a good starting point for engineers to implement their own settings.

### Rest API
The rest api does not play very nice with the automated value discovery, this is due to the nested dictionary structure. It would be nice to have something that corresponds to this jaffle shop config:

```py
source = rest_api_source(
    {
        "client": {
            "base_url": "https://jaffle-shop.dlthub.com/api/v1/",
                "paginator": {
                    "type": "header_link",
                },
            },
            "resources": [
                "customers",
                "products",
            ],
        },
    )
```

in the dlt.yml as the result of an instantiation.

### SQL Database

As a starting point, let's try to replicate it so it will sync the familes from the genome database, see the example pipeline script for this. I think we could also host a jaffle shop postgres database for a few bucks a months, but that would be the next step, first let's try to get the code in order.

### Filesystem

We could probably add a filesystem that just points to a local folder. This is tbd.

**Comment by rudolfix** [comment]
REST API has a different signature than above and it will be easier to provide defaults:
```py
@decorators.source
def rest_api(
    client: ClientConfig = dlt.config.value,
    resources: List[Union[str, EndpointResource, DltResource]] = dlt.config.value,
    resource_defaults: Optional[EndpointResourceBase] = None,
) -> List[DltResource]:
```
but those defaults will look nice in `yaml` format. if we will put them into `toml` config it won't look good and will be something that is not even documented.
Maybe: if we generate a sample configuration and it does not contain any secrets then we should place it in `config.toml` and for now in OSS we skip that?

right now I get something like this:
```toml
[sources.rest_api]
resources = ["a", "b", "c"] # please set me up!
[sources.rest_api.client] # please set me up!
key = "value"
```

**SQL Database**
Here we have two options:
1. generate config like below
```toml
[sources.sql_database.credentials]
drivername = "drivername" # please set me up!
database = "database" # please set me up!
password = "password" # please set me up!
username = "username" # please set me up!
host = "host" # please set me up!
port = 0 # please set me up!
```
but with placeholders that make it completely clear that they are wrongly configured. I also had an idea that we can use something like
`drivername = "#please set me up1"
and if we see this in `resolve_confg` we treat that as unresolved variable and issue a special warning. WDYT?

btw. in config.toml I get
```toml
[sources.sql_database]
table = "table" # please set me up!
```
this is baaad

2. option 2. we use `__config_gen_annotations__` to say that we want a default on the whole config so we can show connection string like
`mysql+pymsql://host:port/database` etc.

We could also allow people to do `dlt init sql_database[mysql]` and then we generate mysql example. WDYT? can be encoded in `__config_gen_annotations__` as well

**Filesystem**
Here it would be cool to somehow let people tell us bucket type ie. `filesystem[az]`. and below we generate az://bucket/path not this
```toml
[sources.filesystem]
bucket_url = "bucket_url" # please set me up!
```
and right credentials, not s3:
```toml
[sources.filesystem.credentials]
aws_access_key_id = "aws_access_key_id" # please set me up!
aws_secret_access_key = "aws_secret_access_key" # please set me up!
```
