### ISSUE TITLE
Create an example on how to use the REST API configuration in the dlt+ YAML

### ISSUE THREAD

**Issue by VioletM** [dlt-hub/dlt#2784]
### Documentation description

We should create a full example of configuring REST API source through YAML. For example:

```yml
  jaffle_shop:
    type: rest_api
    client:
      base_url: # Insert API base URL here
      paginator: auto
    resource_defaults:
      write_disposition: replace
    resources:
      - customers
      - # Add up to 4 more bulk endpoints
      -
        name: orders
        endpoint:
          path: orders
          params:
            start_date:
              type: incremental
              cursor_path: # What field in the response contains the timestamp? 
        write_disposition: append
```
But describing the full variety of parameters

### Are you a dlt user?

None
