### ISSUE TITLE
allow to change destination capabilities

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#964]
**Background**
Some of the destination capabilities may be changed by the user, for example:
- default decimal, integer, text or timestamp precision
- naming convention

ideally we would allow user to change certain via `capabilities` of `Destination` and via configuration ie
```toml
[destination.postgres.capabilities]
decimal_precision="9,3"
naming_convention="duck_case"
```

**Requirements**
1. * [ ] allow the capabilities to be set via property of Destination
2. * [ ] create base capabilities that can be a part of configuration with settings for which configuration make sense
3. * [ ] write tests
4. * [ ] document both methods in Destination docs
