### ISSUE TITLE
Vertica destination support

### ISSUE THREAD

**Issue by perttus** [dlt-hub/dlt#991]
### Feature description

Is it possible to add support for Vertica as destination?

### Are you a dlt user?

I'd consider using dlt, but it's lacking a feature I need.

### Use case

Replace Informatica

**Comment by perttus** [comment]
I tried it with Postgres adapter since the dialect is very similar to Vertica. However, that didn't work out of the box. I get error
> <class 'psycopg2.OperationalError'>
server didn't return client encoding

I used [Vertica docker](https://hub.docker.com/r/vertica/vertica-ce) for testing together with [chess pipeline example](https://dlthub.com/docs/dlt-ecosystem/destinations/postgres)

```toml
[destination.postgres.credentials]
database = "verticatest"
password = ""
username = "dbadmin"
host = "localhost"
port = 5433
connect_timeout = 15
``` 

Where should I input the database schema or is `dataset_name` used for that?

There's already support for Vertica in [DBT](https://github.com/vertica/dbt-vertica/tree/master) and [Airbyte](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-vertica/src/main/java/io/airbyte/integrations/destination/vertica/VerticaDestination.java) which is great. Maybe those implementations could be used to fix the connections issue here.
